# Generated by Django 3.0.3 on 2020-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200921_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
